# Generated by Django 4.2.10 on 2024-03-15 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_bank_account_profile_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='iban',
            field=models.CharField(default='', max_length=32, validators=[django.core.validators.RegexValidator('^[A-Z]{2}[0-9]*$')]),
        ),
    ]
