# Generated by Django 5.0 on 2024-01-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='app',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
