# Generated by Django 4.2.10 on 2024-04-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url_feedback',
            field=models.SlugField(default=''),
        ),
    ]
