# Generated by Django 4.2.10 on 2025-12-01 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_url_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url_feedback',
            field=models.SlugField(default='', validators=[django.core.validators.RegexValidator('^[a-z0-9_-]+$', 'Enter a valid slug.')]),
        ),
    ]
