# Generated by Django 4.2.10 on 2024-03-10 16:58

import bank.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('country', models.CharField(choices=[('PL', 'Poland'), ('US', 'United States'), ('UK', 'United Kingdom')], max_length=50)),
                ('iban', models.CharField(max_length=32, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$'), django.core.validators.MinLengthValidator(16)])),
                ('cvc', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
                ('valid_until', models.DateTimeField(default=bank.models.default_valid_until)),
                ('is_valid', models.BooleanField(default=True)),
                ('logo', models.CharField(default='Visa', max_length=20)),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'deposit'), ('WITHDRAWAL', 'withdrwal'), ('TRANSFER', 'transfer')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('iban', models.CharField(max_length=32, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction date')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='MasterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$'), django.core.validators.MinLengthValidator(16)])),
                ('cvc', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
                ('valid_until', models.DateTimeField(default=bank.models.default_valid_until)),
                ('is_valid', models.BooleanField(default=True)),
                ('logo', models.CharField(default='Master Card', max_length=20)),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
