# Generated by Django 4.2.10 on 2024-03-15 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='iban',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}[0-9]*$')]),
        ),
    ]
