# Generated by Django 4.2.10 on 2024-03-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_bank_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='country',
            field=models.CharField(choices=[('PL', 'Poland'), ('DE', 'Germany'), ('GB', 'United Kingdom')], max_length=50),
        ),
    ]
