# Generated by Django 4.2.10 on 2024-04-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_bank_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='iban',
            field=models.CharField(max_length=32),
        ),
    ]
