# Generated by Django 4.2.10 on 2025-11-20 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_mastercard_valid_until_alter_visa_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercard',
            name='cvc',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='visa',
            name='cvc',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$')]),
        ),
    ]
