# Generated by Django 4.2.10 on 2025-01-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='redirect_link',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
